input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "microservice-logs-%{+YYYY.MM.dd}"
  }
  # Menampilkan log di terminal Docker agar mudah di-debug
  stdout { codec => rubydebug }
}