input {

  tcp {

    port => 5044

    codec => json

  }

}

filter {

  mutate {

    add_field => {

      "project" => "Microservice Monitoring"

    }

  }

}

output {

  elasticsearch {

    hosts => ["http://elasticsearch:9200"]

    index => "microservice-logs-%{+YYYY.MM.dd}"

  }

  stdout {

    codec => rubydebug

  }

}